### ISSUE TITLE
crashed in xcode 7.3 

### ISSUE THREAD

**Issue by zhengying** [schickling/Device.swift#13]
crashed in xcode 7.3 here:

...
let mirror = Mirror(reflecting: machine)
...

**Comment by schickling** [comment]
I'm sorry, I can't fix this right now. Would you be up for submitting a PR? :+1:

**Comment by zhengying** [comment]
It's a bug in swift 2.2
iOS7 will crash when create a mirror object by Mirror(reflecting:) 
I submit a issue to Apple https://bugs.swift.org/browse/SR-1036

**Comment by schickling** [comment]
A thanks for the update!
