### ISSUE TITLE
Iphone 5SE and Ipad Pro

### ISSUE THREAD

**Issue by darkbit34** [schickling/Device.swift#14]
Among the various types of devices are not present "Iphone SE" and "iPad Pro"

**Comment by schickling** [comment]
Mind adding them via a PR?

**Comment by darkbit34** [comment]
I'm a beginner I do not know what you mean :) I changed my project but I'd also would update the library ...

**Comment by schickling** [comment]
This should help: https://help.github.com/articles/creating-a-pull-request/ :+1:
