### ISSUE TITLE
Issue compiling on Xcode 8

### ISSUE THREAD

**Issue by gabrielcandiag** [schickling/Device.swift#19]
I'm having this issue when i try to run the App on Xcode 8. 

Anyone else is seeing this?.

<img width="823" alt="screen shot 2016-09-07 at 12 34 41 pm" src="https://cloud.githubusercontent.com/assets/10672431/18318313/a57c7c9e-74f7-11e6-907f-ed68b67f3c1a.png">

**Comment by codytwinton** [comment]
This issue is resolved with the latest version.
