### ISSUE TITLE
Cut a release with Swift 3.0 support to Cocoapods

### ISSUE THREAD

**Issue by RyanRamchandar** [schickling/Device.swift#21]
Xcode 8 is now released and there are build errors when using the latest pod (Device.swift 0.3.1) with Swift 3.0 as seen in #19 .

**Comment by RyanRamchandar** [comment]
In the mean time you can use the following as a workaround in your `Podfile`, since support is in `master` just not released as a pod yet:

`pod 'Device.swift', :git => 'https://github.com/schickling/Device.swift.git', :branch => 'master'`

**Comment by schickling** [comment]
Unfortunately I don't have to time at the moment to actively maintain this repository but I've added you as a collaborator. Please feel free to move forward with this!

**Comment by RyanRamchandar** [comment]
Great. I'll update this when I get a moment.

**Comment by RyanRamchandar** [comment]
The podspec is at 0.3.2 already and I added a tag for it also to the latest commit 1eadcde

@schickling if you are the one who initially pushed the pod you will need to do it again unless you add another contributor.
https://guides.cocoapods.org/making/getting-setup-with-trunk#adding-other-people-as-contributors

**Comment by codytwinton** [comment]
+1 on this. The Pod trunk is still version `0.3.1` containing `Swift 2.3` code

**Comment by schickling** [comment]
@RyanRamchandar I think someone else published it via Pods. Back then I've just use carthage.

**Comment by codytwinton** [comment]
@RyanRamchandar Any update on `pod trunk push Device.swift.podspec` for the new version?

**Comment by RyanRamchandar** [comment]
@codytwinton unfortunately I am not a contributor to the pod, and thus can't push it there.

We may need to create a new pod if the current one has become orphaned.

**Comment by codytwinton** [comment]
@RyanRamchandar Good to know. I'll reach out to @schickling at `schickling.j@gmail.com` and see what response I can get.

**Comment by schickling** [comment]
Bad news I guess. Don't really know who `efremidzel@hotmail.com` is. Maybe you guys should reach out to him.

![image](https://cloud.githubusercontent.com/assets/1567498/20455209/b29c73aa-ae56-11e6-9778-ea434fe2d5e7.png)

**Comment by codytwinton** [comment]
@schickling - Good to know. I posted a contesting of ownership on trunk.cocoapods.org so the pod can go back into your name.

We'll see how that goes…

**Comment by schickling** [comment]
![image](https://cloud.githubusercontent.com/assets/1567498/20461676/579f02f6-af05-11e6-858b-03421616435c.png)

🎉

**Comment by codytwinton** [comment]
New Version supporting `Swift 3.0` has been pushed.

**Comment by RyanRamchandar** [comment]
Thanks @codytwinton for taking the initiative on this. Great job!

**Comment by codytwinton** [comment]
@RyanRamchandar - Absolutely! Also, I created a Pull Request here: #26 

Can you take a look and see what you think? Don't want to merge the code without a second pair of eyes to look over the code.
