### ISSUE TITLE
Missing iPod Touch 6th Gen Support

### ISSUE THREAD

**Issue by Laptopmini** [schickling/Device.swift#30]
https://github.com/Laptopmini/Device.swift/commit/4f8e4621b53a5c5f2ce1a8aad3f00fba5bb916a1

**Comment by codytwinton** [comment]
@Laptopmini Thanks for catching this! If you submit a pull request, I'll merge this in.

**Comment by Laptopmini** [comment]
I have other changes in my branch, you'll have to cherry pick it.

**Comment by codytwinton** [comment]
I don't personally have time to add this, but if you re-fork this repo, you can add in your changes and submit as a pull request.
