### ISSUE TITLE
Update tag + upload podspec to common repo.

### ISSUE THREAD

**Issue by igorkislyuk** [schickling/Device.swift#32]
Hi, there you are merged my PR. Thanks. Hope you soon set the proper tag and upload podspec to common CocoaPod repo.

**Comment by schickling** [comment]
I'd be happy to add you as a maintainer to take care of this, since I'm currently not using this project.

**Comment by codytwinton** [comment]
@schickling @igorkislyuk I can also handle this, if necessary.

**Comment by igorkislyuk** [comment]
@schickling @codytwinton If @codytwinton ready to do this, that's fine. If not - I can take care of it later.

**Comment by schickling** [comment]
I've added you @igorkislyuk. Leave it up to you and @codytwinton how to proceed.

**Comment by igorkislyuk** [comment]
@schickling Already done it. But there is a little problem.

```
You (igorkislyuk@icloud.com) are not allowed to push new versions for this pod. The owners of this pod are cody.t.winton@gmail.com and schickling.j@gmail.com
```

You should give me access to push podspec or push it yourself just downloading the `master` branch

**Comment by igorkislyuk** [comment]
@schickling Any solutions about this problem?

**Comment by schickling** [comment]
@codytwinton would be great if you could take care of it. I haven't touch pods in ages!

**Comment by codytwinton** [comment]
I'm on it. @igorkislyuk I'll add you to the Podspec so you can also push.

**Comment by codytwinton** [comment]
@igorkislyuk you're now an owner on the podspec, so now you may successfully push the latest podspec.

**Comment by igorkislyuk** [comment]
@codytwinton Thanks. I've pushed the [latest](https://cocoapods.org/pods/Device.swift) podspec. It could be closed
