### ISSUE TITLE
Add Prebuilt Binary For Carthage

### ISSUE THREAD

**Issue by jakewelton** [schickling/Device.swift#37]
It would be nice to have prebuilt binaries attached to releases. This allows Carthage to pull those files rather than building from source each time. This is especially useful in CI environments and would help reduce build times.

**Comment by codytwinton** [comment]
Good idea. I'll try to get to this, but if someone else wants to take this on...

**Comment by jakewelton** [comment]
I would happily update a binary for this, however, unfortunately I don't have the correct level of access to do so :(

I believe whenever a release is made, the person making the release needs to attach the binary (or have a CI process in place to do it automatically)

**Comment by codytwinton** [comment]
@jakewelton - I'm fine with that, but this isn't my repo. I wanna respect @schickling in this decision.

**Comment by jakewelton** [comment]
I agree @codytwinton. Would be good to get @schickling's opinion on this.

**Comment by igorkislyuk** [comment]
Because of our releases that still made by hand, I manually added prebuilt binary for 1.2.1. Hope for next releases it won't be forgotten. Use [this instruction](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) as a reminder
