### ISSUE TITLE
EXC_BAD_ACCESS for EnumProtocol .all

### ISSUE THREAD

**Issue by jwelton** [schickling/Device.swift#38]
I've started to get a crash for the EnumProtocol `.all` implementation. It's crashing on line 235 in `UIDeviceExtension.swift`. I think this has started happening with the latest version of Xcode (Version 9.3 (9E145)).

Test all seem to run fine, however, once the library is integrated into a project, trying to access something such as deviceType, causes this runtime crash.

I've integrated using Carthage. Not sure if this problem also happens when using Cocoapods.

I've built an example app, demonstrating this problem. You can find it here: https://github.com/jwelton/Device.swift/tree/example-app

**Comment by codytwinton** [comment]
@jwelton I'm doing some investigation. Stay tuned...

**Comment by codytwinton** [comment]
@jwelton I've attempted to resolve this issue in pull request #39 

You can also view the code directly on the [`cleanup`](https://github.com/schickling/Device.swift/tree/cleanup) branch.
