### ISSUE TITLE
Support for Swift 4.2 and iOS 12

### ISSUE THREAD

**Issue by furiosFast** [schickling/Device.swift#45]
Hello,
there is an error in the code when you run the app on the simulator, that is: the case is no longer recognized when the app is on the simulator.
All is returned with "notAvailable"

**Comment by codytwinton** [comment]
@furiosFast - Thanks for reporting this issue! I am personally unable to address this right away, but please feel free to submit a pull request.

**Comment by furiosFast** [comment]
here is the solution (found by V8tr): https://github.com/V8tr/Device.swift/commit/7ddfe300207a834efe3594058f31dbc058cbf9ff

**Comment by igorkislyuk** [comment]
Hi all, does this still reproduce?

**Comment by codytwinton** [comment]
Not to my knowledge...

**Comment by igorkislyuk** [comment]
I checked it. All is ok. Can be reopened if needed
