### ISSUE TITLE
Support iPad 5th and 6th

### ISSUE THREAD

**Issue by madhwang** [schickling/Device.swift#49]
Hello!

The UIDeviceExtension.swift file does not appear to return accurate values for ipad 5th generation and ipad 6th generation.
I would appreciate it if you add these two devices.

Thanks!

**Comment by iSapozhnik** [comment]
@madhwang just made a PR for that.
https://github.com/schickling/Device.swift/pull/50

**Comment by codytwinton** [comment]
This has been resolved with #50
