### ISSUE TITLE
Release 1.1.3 with support for newer iPhone versions

### ISSUE THREAD

**Issue by chrs1885** [schickling/Device.swift#51]
Can you please trigger a new release of the current master and push the pod to the trunk?

Thank you!

**Comment by JonCox** [comment]
+1

**Comment by igorkislyuk** [comment]
Hi, thanks you for opening this issue. Which iPhone versions should we support?

**Comment by JonCox** [comment]
All of them 😝 The latest versions (XS, XR & XS Max) are already supported in the master branch, but for using CocoaPods a new release needs to be made so pods can automatically update to use the latest master branch changes.

**Comment by igorkislyuk** [comment]
Ok, I got this. Will fix soon, sorry

**Comment by igorkislyuk** [comment]
Hi, guys. I made release 1.2. Additional checks appreciated
