### ISSUE TITLE
import Device_swift

### ISSUE THREAD

**Issue by RyanRamchandar** [schickling/Device.swift#6]
I had to call

```
import Device_swift
```

instead of

```
import Device
```

**Comment by schickling** [comment]
Did you install the package via Pods?

**Comment by RyanRamchandar** [comment]
Yes

**Comment by schickling** [comment]
Sorry about that. I don't use Cocoapods. The support was added through a PR.

**Comment by RyanRamchandar** [comment]
That's okay. I let you know so others are aware.

**Comment by schickling** [comment]
Thanks!
