### ISSUE TITLE
Identifier for iphone 6s and 6s+ are mixed up

### ISSUE THREAD

**Issue by iamzoltanvaradi** [schickling/Device.swift#9]
For some reason iPhone7,2 is a the iPhone 6 and iPhone7,1 is the iPhone 6 plus, but iPhone8,2 is NOT the iPhone 6s, but the iPhone 6s plus. I don't know why apple stopped following its own pattern here, but as a result, 6s is identified as 6s+ and 6s+ is identified as a 6s.
Ref: https://www.theiphonewiki.com/wiki/Models

**Comment by schickling** [comment]
Would you like to create a PR for this? :+1:

**Comment by eddieespinal** [comment]
I had the same issue and took me some times to really discover what was wrong with my codes when in fact it was due to this mixed up on your library.  Can you please fix it before someone else that wants to use it has to spend valuable time troubleshooting issues due to this problem.  Thanks.

**Comment by schickling** [comment]
@eddieespinal Would you like to create a PR for this? 👍

**Comment by schickling** [comment]
Thanks @eddieespinal
